name: bigfoot-streamlit
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
      - streamlit
      - streamlit-folium
      - black
      - flake8
      - pandas
      - numpy
      - python-dateutil
